### ISSUE TITLE
3.2 support? I get "The selected extension cannot be enabled, please verify the extension’s requirements."

### ISSUE THREAD

**Issue by rusefi** [kinerity/fulllinks#1]
When I try to enable on 3.2.9

**Comment by rusefi** [comment]
I have modified composer.json
```{
    "name": "kinerity/fulllinks",
    "type": "phpbb-extension",
    "description": "n/a",
    "homepage": "https://www.project-w.org/",
    "version": "1.0.0-dev",
    "time": "2020-01-01",
    "license": "GPL-2.0-only",
    "authors": [
        {
            "name": "Kailey Truscott",
            "email": "",
            "homepage": "https://www.layer-3.org/",
            "role": "Extension Developer"
        }
    ],
    "require": {
        "php": ">=5.3.3",
        "phpbb/phpbb": ">=3.1.2"
    },
    "extra": {
        "display-name": "Full Links",
        "soft-require": {
            "phpbb/phpbb": ">=3.1.2"
        }
    }
}
```
![image](https://user-images.githubusercontent.com/7377949/82461877-df408a00-9a88-11ea-8bc8-0a7b1348544c.png)

but it still refuses to install, I am puzzled :)

**Comment by rusefi** [comment]
https://www.phpbb.com/customise/db/extension/full_links/ worked for me, sorry for not noticing it

**Comment by kinerity** [comment]
> https://www.phpbb.com/customise/db/extension/full_links/ worked for me, sorry for not noticing it

Yeah, you were getting blocked [here](https://github.com/kinerity/fulllinks/blob/master/ext.php#L32)

**Comment by rusefi** [comment]
why not rely on the standard mechanism - does the standard mechanism not enforce anything?

if this duplication is needed would it be nice to comment in composer.json stating an unusual validation mechanism?

**Comment by rusefi** [comment]
PS: just curious, I am a totally happy camper do not get me wrong :) I have my own tiny extension so my "phpbb developer" part is curious.
